plugins:
  required:
    ant: latest
    authentication-tokens: latest
    blueocean: latest
    awseb-deployment-plugin: latest
    backup: latest
    badge: latest
    branch-api: latest
    config-file-provider: latest
    cloudbees-bitbucket-branch-source: latest
    chromedriver: latest
    credentials: latest
    aws-credentials: latest
    cobertura: latest
    aws-java-sdk: latest
    code-coverage-api: latest
    cvs: latest
    docker-workflow: latest
    docker-commons: latest
    email-ext: latest
    envinject: latest
    envinject-api: latest
    extensible-choice-parameter: latest
    git: latest
    git-server: latest
    git-client: latest
    github: latest
    greenballs: latest
    groovy: latest
    http_request: latest
    icon-shim: latest
    javadoc: latest
    junit: latest
    jira: latest
    jquery: latest
    jquery-ui: latest
    ldap: latest
    maven-plugin: latest
    mapdb-api: latest
    mask-passwords: latest
    mailer: latest
    m2release: latest
    mercurial: latest
    nodejs: latest
    dependency-check-jenkins-plugin: latest
    dependency-track: latest
    pam-auth: latest
    plain-credentials: latest
    workflow-api: latest
    workflow-aggregator: latest
    lockable-resources: latest
    htmlpublisher: latest
    pipeline-utility-steps: latest
    pipeline-github-lib: latest
    workflow-multibranch: latest
    publish-over-ftp: latest
    publish-over-ssh: latest
    release: latest
    saferestart: latest
    matrix-auth: latest
    matrix-project: latest
    cloudbees-folder: latest
    sonar: latest
    ssh-agent: latest
    thinBackup: latest
    translation: latest
